# ruff: noqa: E501
import logging
from datetime import datetime

from backend.api.schemas.tasks import AnalysisResult

logger = logging.getLogger(__name__)

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; font-size: 12px; color: #1a1a1a; margin: 40px; }}
  h1 {{ font-size: 22px; font-weight: bold; color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; }}
  h2 {{ font-size: 14px; font-weight: bold; color: #16213e; margin-top: 24px; }}
  .meta {{ color: #666; font-size: 11px; margin-top: 4px; }}
  .summary {{ background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 6px;
              padding: 16px; margin: 16px 0; display: flex; gap: 32px; }}
  .stat {{ text-align: center; }}
  .stat-value {{ font-size: 28px; font-weight: bold; }}
  .stat-label {{ font-size: 10px; color: #666; text-transform: uppercase; }}
  .high {{ color: #dc2626; }}
  .medium {{ color: #d97706; }}
  .low {{ color: #16a34a; }}
  .clause {{ border: 1px solid #dee2e6; border-radius: 6px; margin: 12px 0; padding: 14px; }}
  .clause-header {{ display: flex; gap: 8px; align-items: center; margin-bottom: 8px; }}
  .badge {{ font-size: 10px; font-weight: bold; padding: 2px 8px; border-radius: 12px;
            text-transform: uppercase; }}
  .badge-high {{ background: #fef2f2; color: #dc2626; }}
  .badge-medium {{ background: #fffbeb; color: #d97706; }}
  .badge-low {{ background: #f0fdf4; color: #16a34a; }}
  .clause-type {{ font-size: 10px; color: #888; }}
  .clause-text {{ font-size: 11px; color: #333; background: #f9f9f9;
                  padding: 8px; border-radius: 4px; line-height: 1.5; }}
  .clause-explanation {{ font-size: 11px; color: #555; margin-top: 6px; }}
  .disclaimer {{ margin-top: 32px; font-size: 10px; color: #999; font-style: italic;
                 border-top: 1px solid #eee; padding-top: 12px; }}
  .errors {{ background: #fff5f5; border: 1px solid #fed7d7; border-radius: 6px;
             padding: 12px; margin: 12px 0; font-size: 11px; color: #c53030; }}
</style>
</head>
<body>
<h1>⚖️ LegalLens Contract Risk Report</h1>
<p class="meta">
  File: <strong>{filename}</strong> &nbsp;|&nbsp;
  Generated: {generated_at} &nbsp;|&nbsp;
  Analysis time: {processing_time}s
</p>

<h2>Executive Summary</h2>
<div class="summary">
  <div class="stat">
    <div class="stat-value" style="color:{score_color}">{overall_score}%</div>
    <div class="stat-label">Overall Risk</div>
  </div>
  <div class="stat">
    <div class="stat-value high">{high_count}</div>
    <div class="stat-label">High Risk</div>
  </div>
  <div class="stat">
    <div class="stat-value medium">{medium_count}</div>
    <div class="stat-label">Medium Risk</div>
  </div>
  <div class="stat">
    <div class="stat-value low">{low_count}</div>
    <div class="stat-label">Low Risk</div>
  </div>
  <div class="stat">
    <div class="stat-value" style="color:#555">{total_count}</div>
    <div class="stat-label">Total Clauses</div>
  </div>
</div>

{errors_section}

<h2>Clause Analysis</h2>
{clauses_html}

<div class="disclaimer">
  This report is generated by AI and is not legal advice. LegalLens may make errors.
  Always consult a qualified attorney before signing any contract.
  Generated by LegalLens — open-source AI contract analyzer.
</div>
</body>
</html>
"""

_CLAUSE_TEMPLATE = """\
<div class="clause">
  <div class="clause-header">
    <span class="badge badge-{risk_level}">{risk_level_upper} — {risk_score}%</span>
    <span class="clause-type">{clause_type}</span>
  </div>
  <div class="clause-text">{clause_text}</div>
  <div class="clause-explanation">{risk_explanation}</div>
</div>
"""


def generate_report_html(result: AnalysisResult) -> str:
    """Generate an HTML report from an analysis result.

    Args:
        result: Completed analysis result.

    Returns:
        HTML string ready to be rendered or converted to PDF.
    """
    score_pct = round(result.overall_risk_score * 100)
    score_color = (
        "#dc2626" if score_pct >= 60 else "#d97706" if score_pct >= 35 else "#16a34a"
    )

    clauses_html = ""
    for clause in sorted(
        result.clauses,
        key=lambda c: {"high": 0, "medium": 1, "low": 2}[c.risk_level],
    ):
        clause_type = clause.clause_type.replace("_", " ").title()
        clauses_html += _CLAUSE_TEMPLATE.format(
            risk_level=clause.risk_level,
            risk_level_upper=clause.risk_level.upper(),
            risk_score=round(clause.risk_score * 100),
            clause_type=clause_type,
            clause_text=clause.text.replace("<", "&lt;").replace(">", "&gt;"),
            risk_explanation=clause.risk_explanation.replace("<", "&lt;").replace(">", "&gt;"),
        )

    if not clauses_html:
        clauses_html = "<p style='color:#888'>No significant clauses identified.</p>"

    errors_section = ""

    return _HTML_TEMPLATE.format(
        filename=result.filename,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        processing_time=result.processing_time_seconds,
        score_color=score_color,
        overall_score=score_pct,
        high_count=result.high_risk_count,
        medium_count=result.medium_risk_count,
        low_count=result.low_risk_count,
        total_count=len(result.clauses),
        errors_section=errors_section,
        clauses_html=clauses_html,
    )


def generate_report_pdf(result: AnalysisResult) -> bytes:
    """Generate a PDF report from an analysis result using WeasyPrint.

    Args:
        result: Completed analysis result.

    Returns:
        PDF bytes.

    Raises:
        ImportError: If WeasyPrint is not installed.
    """
    try:
        from weasyprint import HTML
    except ImportError as exc:
        raise ImportError(
            "WeasyPrint is required for PDF generation. "
            "Install it with: pip install weasyprint"
        ) from exc

    html = generate_report_html(result)
    return HTML(string=html).write_pdf()
